#!/usr/bin/env python

import pyzed.sl as sl
import math
import numpy as np
import sys
import cv2

def main():

    ##################################################
    ##                ZED params                    ##
    ##################################################

    # Create a Camera object
    zed = sl.Camera()

    # Create a InitParameters object and set configuration parameters
    init_params = sl.InitParameters()
    init_params.depth_mode = sl.DEPTH_MODE.PERFORMANCE  # Use PERFORMANCE depth mode
    init_params.coordinate_units = sl.UNIT.METER  # Use meter units (for depth measurements)
    init_params.camera_resolution = sl.RESOLUTION.HD720

    # Open the camera
    err = zed.open(init_params)
    if err != sl.ERROR_CODE.SUCCESS:
        exit(1)

    # Create and set RuntimeParameters after opening the camera
    runtime_parameters = sl.RuntimeParameters()
    runtime_parameters.sensing_mode = sl.SENSING_MODE.STANDARD  # Use STANDARD sensing mode
    # Setting the depth confidence parameters
    runtime_parameters.confidence_threshold = 100 # original: 100
    runtime_parameters.textureness_confidence_threshold = 100


    ##################################################
    ##                main loop                     ##
    ##################################################

    while True:

        # Create an RGBA sl.Mat object
        image_depth_zed = sl.Mat(zed.get_camera_information().camera_resolution.width, zed.get_camera_information().camera_resolution.height, sl.MAT_TYPE.F32_C1)

        if zed.grab() == sl.ERROR_CODE.SUCCESS :
            # Retrieve the normalized depth image
            zed.retrieve_image(image_depth_zed, sl.VIEW.DEPTH)
            # Use get_data() to get the numpy array
            image_depth_ocv = image_depth_zed.get_data()
            # Display the depth view from the numpy array
            cv2.imshow("Image", image_depth_ocv)

        if cv2.waitKey(30) >= 0 :
            break

    # Close the camera
    zed.close()

if __name__ == "__main__":
    main()


